# Matrix Decomposition

This notebook covers common matrix decomposition methods used in machine learning:
- QR Decomposition
- Eigen Decomposition
- Singular Value Decomposition (SVD)

In [4]:
import numpy as np

def qr_decomposition(vectors):
    """
    Perform QR decomposition via Gram-Schmidt on a set of vectors

    Args:
        vectors: A 2D np.array (n, m), where each column is a vector of length n

    Returns:
        The orthonormal basis and upper triangular matrix of scalary projections of
        each original vector onto the orthonormal basis
    """
    n, m = vectors.shape
    A = vectors.copy().astype(float)
    Q = np.zeros((n, m)).astype(float)
    R = np.zeros((m, m)).astype(float)

    # We can normalize beforehand to simplify projecting each vector onto every other vector
    # But that may lead to floating point errors, so let's prefer the standard method
    for j1 in range(m):
        vec_j1 = A[:, j1].copy()

        # Subtract projections of vec_j1 on previous vectors
        ortho_vec_j1 = A[:, j1].copy()
        for j2 in range(j1):
            vec_j2 = Q[:, j2].copy()

            # Normalize vec_j2
            mag_j2 = np.sqrt(np.sum(vec_j2 * vec_j2))
            norm_vec_j2 = vec_j2 / mag_j2

            # Get the scalar projection of vec_j1 onto vec_j2:
            # The scalar projection is typically vec_j1 @ vec_j2 / ||vec_j2||
            # But we have the normalized vector of vec_j2
            # And vec_j1 @ norm_vec_j2 = ||vec_j1|| * ||norm_vec_j2|| * cos(theta) = ||vec_j1|| * cos(theta)
            # Because vec_j1 is the hypotenus and cos(theta) = adj / hyp
            # Thus, ||vec_j1|| * cos(theta) = length of adj = length of vec_j1 projected onto norm_vec_j2
            # "A unit vector’s components are the cosines of its angles with the coordinate axes."
            scalar_proj_j1 = np.dot(vec_j1, norm_vec_j2)
            
            # Store the scalar projection of the original vector onto norm_vec_j2
            R[j2][j1] = scalar_proj_j1

            # Project vec_j1 onto vec_j2
            proj_j1_onto_j2 = scalar_proj_j1 * norm_vec_j2

            # Subtract the projection from ortho_vec_j1
            ortho_vec_j1 -= proj_j1_onto_j2

        # Normalize ortho_vec_j1
        mag_ortho_j1 = np.sqrt(np.sum(ortho_vec_j1 * ortho_vec_j1))
        orthonorm_vec_j1 = ortho_vec_j1 / mag_ortho_j1
        R[j1][j1] = mag_ortho_j1

        # Add orthonormal basis vector to Q
        Q[:, j1] = orthonorm_vec_j1

    return Q, R


sample_vectors = np.array([[1, 2], 
                           [0, 2]])
Q, R = qr_decomposition(sample_vectors)
print('Q: \n', Q)
print('R: \n', R)

sample_vectors = np.array([[1, 1, 0], 
                           [0, 1, 1], 
                           [0, 0, 1]])
Q, R = qr_decomposition(sample_vectors)
print('Q: \n', Q)
print('R: \n', R)

sample_vectors = np.array([[1, 1, 0], 
                           [1, 0, 1], 
                           [0, 1, 1]])
Q, R = qr_decomposition(sample_vectors)
print('Q: \n', Q)
print('R: \n', R)

Q: 
 [[1. 0.]
 [0. 1.]]
R: 
 [[1. 2.]
 [0. 2.]]
Q: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
R: 
 [[1. 1. 0.]
 [0. 1. 1.]
 [0. 0. 1.]]
Q: 
 [[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
R: 
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
